# Generated by Django 3.2.6 on 2021-08-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210820_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='adress',
            new_name='address',
        ),
    ]
